MetPX/sarracenia

doc/sarra.rst

I wrote a very simple client using pika, and figured I'd share it with everyone!

Added dumbed-down Python3 implementation to doc

---

sarra/examples/subscribe/dd_rdps.conf

Update RDPS config

---

sarra/plugins/msg_download_baseurl.py
sarra/plugins/poll_nexrad.py

A pair of plugins that polls/downloads https://s3.amazonaws.com/noaa-nexrad-level2/index.html

aws nexrad mirroring

---

sarra/examples/poll/pollnexrad.conf
sarra/examples/subscribe/downloadnexrad.conf
sarra/plugins/poll_nexrad.py

included sample configs and fixed posting variables, implementing suggestion from #75

Nexrad mirroring

---

doc/UPGRADING.rst
sarra/plugins/line_mode.py
sarra/sr_ftp.py
sarra/sr_poll.py
sarra/sr_sftp.py

The file gets saved under user_cache_dir/.dest_file_index

Wrote a cache based version of determining what the file index is in an ls line

---

sarra/sr_config.py

added --version support

---

sarra/sr_config.py
sarra/sr_instances.py
sarra/sr_util.py

Addresses #92, intended usage described in #91. Renames original file and deletes it after. Returns if the original file doesn't exist

Implements rename config option

---

doc/Hydro_Examples.rst
sarra/examples/poll/pollnoaa.conf
sarra/examples/poll/pollsoapshc.conf
sarra/examples/poll/pollusgs.conf
sarra/examples/subscribe/subnoaa.conf
sarra/examples/subscribe/subsoapshc.conf
sarra/examples/subscribe/subusgs.conf
sarra/plugins/download_noaa.py
sarra/plugins/download_shc_soap.py
sarra/plugins/download_usgs.py
sarra/plugins/poll_noaa.py
sarra/plugins/poll_shc_soap.py
sarra/plugins/poll_usgs.py

Demonstrates a few (publicly accessible) examples from the CANHYS Hydrometric Data use case. Contains polling/downloading plugins and example configs, and an rst with a sample demo to explain how to extend polling/downloading functionality to get files from a web API.  Could probably also write a short blurb for https://github.com/MetPX/sarracenia/blob/master/doc/Prog.rst#polling since it overlaps now? Suggestions welcome

Hydro plugins

---

doc/Dev.rst
test/flow_autoconfig.sh

Added an autoconfiguration script for freshly installed systems
Modified docs in relation to issue #145 and autoconfig script
Corrected typos in doc/Dev.rst

Flow test autoconfig

---

sarra/sr.py

This is cosmetic, but pleasant.  not tested with flow, as it is just sr status (display only.)

adding more counts to sr status output.

---

sarra/examples/shovel/pclean_f90.conf
sarra/examples/shovel/rabbitmqtt_f22.conf
sarra/plugins/accel_scp.py
sarra/plugins/accel_wget.py
sarra/plugins/poll_script.py
sarra/sr.py
sarra/sr_config.py

Small enhancement related to #240 but also #185

Issue240 2

---

sarra/examples/subscribe/WMO_mesh_CMC.conf
sarra/sr_poll.py
sarra/sr_post.py
sarra/sr_subscribe.py

Revert "Removing from_cluster and to_cluster defaulting."
This reverts commit 46a965430c2bc526abeb84ae2624ac9c1ee394dc.

Should not have removed this function.  Putting it back.

---

sarra/sr_message.py

This fix #273 Partflg now default to None as it was before v03 changes

Fixed partflg missing in sr_message.

---

sarra/sr_config.py

#issue329 fix ready to merge
Tested with a dd_amis where I added tls_rigour strict

Fixed tls_rigour strict (without CRL flag).

---

doc/subscriber.rst

Modifications to additional notes / changes to A First Example additions to subscriber.rst. Clarifies where these changes need to be made, one on command line, either in the source configuration.

Update subscriber.rst A First Example

---

sarracenia/instance.py

Fixed the statehost issue by parsing the config before lr
All static flow tests pass, and flakey + dynamic flow tests pass as well as can be expected

V03 wip issue348 2

---

.github/workflows/dynamic_flow.yml
.github/workflows/flakey_flow.yml
.github/workflows/static_flow.yml
sarracenia/moth/amqp.py
travis/flow_autoconfig.sh

fixes many major problem with flakey... good patches...

V03 wip issue407actions

---

.github/workflows/ghcr.yml

Publish ARM64 and AMD64 under the same tag

Publish ghcr images under one tag

---

.github/workflows/flow.yml

Combines work from @petersilva's commit such as 720315f914dfd5b86b74422d705aa8d8e9c8b514, and my experimentation on [v03_wip_issue407actions_combined](https://github.com/MetPX/sarracenia/tree/v03_wip_issue407actions_combined).
Runs static, dynamic and flakey broker tests with Python versions from 3.6 to 3.10, on Ubuntu.
Related to #445.

GitHub Actions - Implement matrix

---

.github/workflows/flow.yml

Will compressing the artifacts into a tar.gz file before the upload-artifact step help reduce the errors we're getting?

Artifacts Issue

---

.github/workflows/flow.yml
travis/flow_autoconfig.sh

https://github.com/MetPX/sarracenia/issues/407#issuecomment-1086559587
edit to trigger run...

Remove `setup-python`, use only default Python version on Ubuntu

---

sarracenia/config.py
sarracenia/flow/__init__.py
sarracenia/flowcb/accept/speedo.py
sarracenia/flowcb/accept/sundewpxroute.py
sarracenia/flowcb/accept/toclusters.py
sarracenia/flowcb/accept/tohttp.py
sarracenia/flowcb/filter/wmo2msc.py
sarracenia/flowcb/gather/file.py
sarracenia/flowcb/housekeeping/resources.py
sarracenia/flowcb/pclean.py
sarracenia/flowcb/poll/__init__.py
sarracenia/flowcb/v2wrapper.py
sarracenia/instance.py
sarracenia/integrity/arbitrary.py
sarracenia/integrity/md5.py
sarracenia/integrity/md5name.py
sarracenia/integrity/random.py
sarracenia/integrity/sha512.py
sarracenia/moth/__init__.py
sarracenia/moth/amqp.py
sarracenia/moth/mqtt.py
sarracenia/moth/pika.py
sarracenia/rabbitmq_admin.py
sarracenia/sr.py
tools/dd-xml-inotify.py
tools/delete_queue.py
tools/queue_manager.py
tools/radar_XFT_messages.py

fixed most syntax errors + unresolved references. #492

V03 wip issue492

---

sarracenia/sr.py

updated config converter. Flow tests pass 31/31, but still the same problem when we use the converter in the tests with 22/31. This is now addressed in issue10 of sr_insects to fix it.

updated converter code (takes care of an extra edge case). #438

---

docs/source/Explanation/CommandLineGuide.rst

V03 wip doc

---

sarracenia/sr.py

- tiny bug I think I saw
- no more errors if a component dir does not exist

V03 wip issue 438

---

sarracenia/config.py

Updated config to adapt chmod_log from v2 vocabulary into v3. assigned to issue523

V03 wip issue523

---

sarracenia/sr.py

https://github.com/MetPX/sarracenia/issues/555. The restart server test was failing because `sr3 stop` would stop foreground posts (polls started using sr3_post and sr3_cpost.
This changes sr3 so that `sr3 stop` (without specific configs specified) never stops any foreground instances, and `sr3 start` also does not start posts that cannot run as daemons.
Foreground possible cases:
* anything with ``foreground`` in its cmd_line is always foreground.
* anything with ``start`` in its cmd_line is always a daemon (not foreground).
* posts and cposts without ``start`` in the cmd_line are always foreground.
* other components without ``start`` or ``foreground`` in the cmd_line are not foreground.
Note: `sr3 stop component/config` will still stop the specified foreground instance.
Posts/cposts …

Changes to sr3 start/stop behaviour to fix #555

---

docs/source/Reference/sr3_options.7.rst
docs/source/fr/Reference/sr3_options.7.rst

simple documentation issue... suggestions welcome.  I think only one reviewer needed... but listed four...
hopefully you don't all have to... not sure how pull requests work.  I omitted the youtube explanation because ... anyone who cares can do the same google query James did...

first stab at #582, explaining --dangerWillRobinson.

---

.github/workflows/v2Flow.yml

Add Ubuntu 22.04 to v2 flow tests

---

Dockerfile_fuse
Dockerfile_fuse_multi

Dockerfile_fuse really is a way to run `sr3` in a container and therefore using any local directories for sr3 config, cache and output directory.  Dockerfile_fuse_multi is a WIP.  Hoping to just copy sr3 and run.

WIP : Dockerfile for Fuse

---

sarracenia/sr.py

Reid found it in senders, and I noticed it in polls on Monday... this needs to be corrected.

default wrong for poll & sender on conversion.

---

docs/source/Reference/sr3_options.7.rst
sarracenia/flowcb/poll/__init__.py
sarracenia/flowcb/post/message.py
sarracenia/sr.py

as per #665 This fixes the problem I had. I wonder if we should put effort into making the built-in parser more adaptable.
Also wondering what we can do to document parser sub-classing for unco-operative upstreams...  This just fixes the specific thing.

V03 issue665

---

sarracenia/flow/__init__.py
sarracenia/flowcb/poll/__init__.py
sarracenia/flowcb/post/message.py

https://github.com/MetPX/sarracenia/issues/667
fix for that...

V03 issue667

---

sarracenia/credentials.py
sarracenia/moth/amqp.py

inscrutable error message encountered during demo.  Now the response is clearer.

V03 issue678

---

sarracenia/config.py

It's a fix, not much to say... offering to a lot of people to review...

fix for #671 wrap regcomp in try/except to clearly deal with bad regex.

---

debian/changelog
doc/sr_postv3.7.rst
sarra/plugins/exp_2mqtt.py
sarra/sr_message.py
sarra/sr_retry.py
sarra/sr_xattr.py

change Integrity to identity in v03 format messages. implement issue #703 for v2 code base.
needs to match sr3 and C implementations.

V2 issue703

---

sarracenia/__init__.py

These were found when developing unit tests

Fix a couple of problems in __init__

---

sarracenia/flow/__init__.py

uh... fixes it to reduce surprise... works like a callback now.

773 destfnscript syntax in configs doesnt work like other flowcb plugins

---

debian/control

@reidsunderland suggestions... for debian packaging recommendations.

Tweak recommends

---

docs/source/Reference/sr3_options.7.rst
docs/source/fr/Reference/sr3_options.7.rst
sarracenia/config.py

* closes #802
duh...adds POST_BROKER_USER variable.

for #802 adds POST_BROKER_USER
