MetPX/sarracenia

doc/UPGRADING.rst, doc/sr_poll.1.rst, sarra/sr_ftp.py, sarra/sr_sftp.py
Changed ls implementations for SFTP/FTP to take ls index of [8:] to be the name of the listing, instead of the last entry by default. Updated corresponding documentation
=> changed sftp/ftp default file index behaviour

doc/UPGRADING.rst, sarra/sr_config.py
Config files can now interpret globbing arguments such as `include *.conf`. Any files that contain *, ?, [ or ] in their names need to be escaped.
=> feature added: config include directive support for globbing #31

sarra/sr_config.py
Suggestion from discussion in #93, continuation of feature request #31
=> Include config option looks at config dir if no matching files are found in the current dir

doc/sr_post.1.rst, doc/sr_post.7.rst, doc/sr_subscribe.1.rst, sarra/sr_config.py, sarra/sr_post.py
Includes documentation for usage/background (I wasn't sure where to stick it, let me know if there's a better place or if there's anything that's missing). Continuation of #54, outline of logic in #119.
`sr_post -header sum=a,65537 <fileName(s)> <configName> start|foreground`
`sr_subscribe -header sum=a,65537 <fileName(s)> <configName> start|foreground`
=> Issue54: Commandline config options for setting checksum xattr

sarra/plugins/file_mail_metareas.py, sarra/plugins/file_send_egc_les.py
Work done for Noureddine. The first plugin emails all incoming bulletins and associated egc info to whatever emails are included as config options, the second sends the associated egc command over telnet based on the telnet credentials in the credentials.conf (user/host specified in "telnet://user@host" format in the config options, does a password lookup from there). Adaptations of old fx scripts. Not sure how useful they'd be to anyone but Noureddine/DI but I figured I should document them here.
=> Two on_file plugins for further bulletin processing

sarra/sr_config.py
Addresses commandline usage for setting sums as discussed in #121. Doesn't necessarily assume the files to set xattrs for are right after the `-header sum=a,sum` option.
=> Issue54: Fixes header evaluation options in sr_config

sarra/sr_subscribe.py
- Fixed the issue with a left strip
- Unified the separate conditions checking if it is win32 in one for both new_relpath and new_dir
- Removed useless debug commented
- Tested on Win 2008 r2
- Flow test passed
=> Now stripping first "/" when in Windows the user specify the drive.

sarra/sr_amqp.py
This issue appeared because .deb default amqp package
for old ubuntu versions (14.04, 16.04) doesnt use the
latest from amqp, so the .connect method does not exist.
=> Fix issue with amqp for older versions (mostly 1.3.3, 1.4.9)

sarra/sr_message.py, sarra/sr_retry.py
- The problem was that when the sum was missing from
the json object it raised key error which was busting
the retry list processing and was emptying it.
- Also using a dict comprehension to remove the sum element
that would be safer in a multi threaded system.
=> Fixed the problem with v03 breaking pc_clean f92.

sarra/sr_message.py, sarra/sr_util.py
#207 
ok il y a des fixes dans cette branche pour corriger le "inplace true"  dans le sender.
Aussi dans la propagation d un sarra ...  message recu avec un partflg I  avec l option implace False
downloaded dans un fichier part  tout fonctionnait  ... mais le message etait reposter avec un I au lieu
d un P   ca aussi ete corriger
=> issue207: MG les fix pour le sender inplace  

sarra/sr_cache.py
quite simple fix... part == None  was missing in test since it can happen with 'R' message
=> MG part=NONE considered now.

doc/Dev.rst, doc/fr/Dev.rst
deprecating release.sh script, as we are now experienced enough to use git directly, and be savvier in our tagging & versioning. It also documents the master branch management discussed in last week's development meeting.  The second commit adds French version of the changes, rest of the commits
are just result of review when seeing how github.com renders the documents.
The major change:  release.sh script incremented the version... but the release is actually the end of version development, not the beginning.  so now we explicitly use git to tag, the completion of work on a version, this allows us to build release information incrementally during development.  The new process also makes explicit what was originally intended, but only suggested in the prior procedure, and rarely done in …
=> revamping master branch management & release process

doc/Dev.rst
work in progress... you can see the result of the first attempt to do a proper release on github.com:
https://github.com/MetPX/sarracenia/releases/tag/v2.19.09b2
There are binaries uploaded at the end.
the release notes are there.
It raises the issue of naming of releases... we have not used release code names before.  Could be fun.
=> notes from 1st try at release done on github.

sarra/sr_poll.py
Issue #275 
sr_poll doesn't crash when attempting to enter an non-existent directory, as previously hypothesized. poll code catches the exception successfully, logs a stack trace, and continues working properly.  
changes: removed stack trace print on caught failed cd exception, purely esthetic, for analyst convenience
=> removed missing directory traceback from debug logs

sarra/sr_message.py
Issue #276 
Tested fix by using a plugin that doesn't include a partstr in message headers, and observing subscriber behaviour. Looking good here, no more TypeErrors.
Flow test passing as well.
=> Issue276: Regression Fix, missing partstr support

doc/fr/sr_poll.1.rst, doc/sr_poll.1.rst, sarra/sr_config.py, sarra/sr_poll.py
We are seeing high load on ddsr nodes since moving the polls from pxatx there.  I think a big part of that is that the polls do not work the way people expect.  what the vip does for sr_poll is stop the nodes from posting, but they still poll. so you have N nodes in a cluster, they all poll, but only one posts.  In many cases, we only need one node to poll (and post) and the state doesn´t matter.  the option added here allows that case.
=> Issue245 - reduce overhead of poll when they don´t have the vip.

doc/dd_subscribe.1.rst, doc/fr/Concepts.rst, doc/fr/Dev.rst, doc/fr/sr_audit.8.rst, doc/fr/sr_sender.1.rst, doc/fr/sr_subscribe.1.rst, doc/fr/sr_watch.1.rst, doc/fr/sr_winnow.8.rst, doc/sr_subscribe.1.rst
I found a few cases where there are extra asterisks in the French and English docs which get rendered instead of making the text bold. Makes some config options a bit easier to understand for new users.
=> Fix confusing asterisks in documentation

sarra/sr_sftp.py
Adding statement to prevent sr_senders from calling init_file_index.
sr_senders do not use the file_index, and calling it requires write permissions to be granted on the receiver else an error is thrown.
Fixes sends to hosts which do not have write permissions enabled on other files/directories.
Related to: #343
=> Add program_name check for file_index creation

sarracenia/sr.py
Fixed sr3 restart by changing resolve
The problem was that reolve wasn't correctly marking processes as stopped, so start never launched anything during restart.
=> Issue 387, fixed sr3 restart

.github/workflows/ghcr.yml
CC: @tomkralidis This PR adds a workflow to publish docker images  of sarracenia any time there is a push to the `v03_wip` branch of sarracenia.
=> Publish docker image to GitHub Container Registry

.github/workflows/dynamic_flow.yml, .github/workflows/flakey_flow.yml, .github/workflows/static_flow.yml
If the artifacts fail to upload, the whole job shouldn't fail.
=> Continue on error for artifacts

.github/workflows/flow.yml, travis/flow_autoconfig.sh
... and Ubuntu 20.04. Ubuntu 22.04 isn't currently available. Ubuntu 18.04 fails due to missing sarrac package... 
```
OK, basic scripting environment is there
No Sarra C package available. Cannot test.
Error: Process completed with exit code 1.
```
=> Use the matrix to run on Ubuntu 18.04

docs/source/Contribution/Documentation.rst, sarracenia/credentials.py
Adds documentation for docstring comments in the code, and completes `credentials.py` docstrings as an example.
Resolves #508.
Other PR, #509 was using the main branch by accident.
=> Docstring documentation and example

sarracenia/moth/amqp.py, sarracenia/sr.py
When Ctrl+C is pressed, the parent process (sr.py) and it's children (instance.py) receive SIGINT. instance.py had a handler that would cleanly stop the flow loop, but sr.py didn't. The `subprocess.run()` call in sr.py normally blocks until instance.py terminates, but because it is in a try...except block, Ctrl+C would interrupt subprocess.run and cause the `except KeyboardError` code to run. 
This PR adds a signal handler (that does nothing except log messages) to instance.py, so when SIGINT is received, the signal handler runs and then returns control back to subprocess.run, allowing the child process to stop cleanly.
---
During flakey tests I also noticed that a message was logged `[ERROR] sarracenia.moth.amqp close sr_amqp/close 2: 'NoneType' object has no attribute 'collect'`. It's …
=> Fix Issue #513: cleanly shutdown subprocesses when a signal is received

.github/workflows/flow.yml
I noticed a few actions runs failed to save artifacts because the log files changed. Since sr3 stop doesn't stop posts anymore, I added an explicit `sr3 stop post/* cpost/*`
=> Stop foreground posts to fix artifact collection

.github/workflows/flow.yml, sarracenia/sr.py
`sr3 stop` will never stop foreground instances, even if you specify `component/config`. A message is printed to let the user know about running foreground configs that were not stopped, and that they can use `--dangerWillRobinson` to stop them.
`sr3 stop --dangerWillRobinson` will always stop running foreground instances (in addition to daemon instances).
Also found that there was a piece missing from previous changes that I made to `sr3 stop`'s behavior. If the stop method started attempting to SIGKILL processes, it would report that foreground instances were not responding to SIGKILL, even though it was not trying to SIGKILL them. Now the processes that are not responding to SIGKILL are correctly reported (only daemone
=> Reworked `sr3 stop` to use dangerWillRobinson

docs/source/Explanation/CommandLineGuide.rst, docs/source/Explanation/Concepts.rst, docs/source/How2Guides/FlowCallbacks.rst, docs/source/How2Guides/source.rst, docs/source/Reference/sr3.1.rst, docs/source/Reference/sr3_options.7.rst, docs/source/fr/CommentFaire/FlowCallbacks.rst, docs/source/fr/CommentFaire/source.rst, docs/source/fr/Explication/Concepts.rst, docs/source/fr/Explication/GuideLigneDeCommande.rst, docs/source/fr/Reference/sr3.1.rst, docs/source/fr/Reference/sr3_options.7.rst, sarracenia/config.py, sarracenia/examples/flow/poll.inc, sarracenia/examples/flow/post.inc, sarracenia/examples/flow/report.inc, sarracenia/examples/flow/sarra.inc, sarracenia/examples/flow/sender.inc, sarracenia/examples/flow/shovel.inc, sarracenia/examples/flow/subscribe.inc, sarracenia/examples/flow/watch.inc, sarracenia/examples/flow/winnow.inc, sarracenia/flow/__init__.py, sarracenia/flowcb/log.py, sarracenia/instance.py, sarracenia/sr.py
so this doesn't do the whole job of the issue, but I think it is useful on it's own, and it lets @andreleblanc11 's stuff work (he's using it in his branch also.)
it adds:
-- the ability to declare flow/  component configurations that are vanilla.
-- the ability to declare flowMain to run arbitrary subclasses of flow making it possible to define all existing components as config files.
-- include files to implement all the existing components.
-- English and French documentation of the above.
=> V03 wip issue575 ... adding "flow" component, and flowMain option.

sarracenia/moth/amqp.py, sarracenia/sr.py
Add `if_unused=True` to exchange delete for #382
Ensure that sr3 cleanup doesn't delete exchanges that have bindings.
@tysonkaufmann found the option in the documentation :)
=> Add `if_unused=True` to exchange delete for #382

sarracenia/flow/__init__.py
Short relPath's were generating unnecessary /'s - not an issue on filesystem but causes issues on http(s) downloads.
Changed download to use os.path calls which will fix issues with short paths.
closes #619
=> Fix double // on relPath download

sarra/sr_poll.py
`dateparser_available` is set to False whether it's successfully imported or not. 
Any time the poll fails to list the remote directory, it will log a misleading error saying that dateparser is not available, even if it is. When a directory fails to be listed for a non-dateparser related reason, it will still log this error message: https://github.com/MetPX/sarracenia/blob/v2_dev/sarra/sr_poll.py#L366-L367
=> Fix dateparser detection bug

sarracenia/__init__.py, sarracenia/moth/__init__.py
over time python3 api examples broke.  
quick fix.  I just put one reviewer because in the last pull request, I saw it wants approval from all before mergeing...
=> fixes for #661 examples of python consumer failing.

sarracenia/__init__.py, sarracenia/config.py, sarracenia/examples/moth_api_consumer.py, sarracenia/examples/moth_api_producer.py, sarracenia/flowcb/v2wrapper.py, sarracenia/moth/amqp.py, sarracenia/moth/mqtt.py, sarracenia/postformat/__init__.py, sarracenia/postformat/v02.py, sarracenia/postformat/v03.py, sarracenia/sr.py
move topic generation away from message protocols and into the payload format code.
the WIS format has a different scheme for determining topic hierarchy, so need a way for the postformat/wis.py to return the "topic" for published messages.
I think the universal idea is that one should be able to determina an appropriate topic from the content of the message.
=> V03 issue617 (part of it.) "topic" depends more on payload format, than message protocol.

docs/source/Tutorials/Install.rst
=> documentation correction for #677

.github/workflows/flow_basic.yml, .github/workflows/flow_mqtt.yml, .github/workflows/flow_redis.yml, .github/workflows/unit-test.yml, debian/changelog, docs/README.rst, docs/requirements.txt, docs/source/Reference/sr3_options.7.rst, docs/source/Reference/sr_post.7.rst, docs/source/fr/Reference/sr3_options.7.rst, docs/source/fr/Reference/sr_post.7.rst, requirements-dev.txt, requirements.txt, sarracenia/__init__.py, sarracenia/config.py, sarracenia/flow/__init__.py, sarracenia/flowcb/accept/trim_legacy_fields.py, sarracenia/flowcb/post/message.py, sarracenia/flowcb/work/delete.py, sarracenia/moth/amqp.py, sarracenia/moth/mqtt.py, sarracenia/postformat/__init__.py, sarracenia/postformat/v02.py, sarracenia/postformat/v03.py, sarracenia/postformat/wis.py, setup.py, travis/flow_autoconfig.sh, travis/flow_autoconfig_add_mosquitto.sh
OK, so finally all the pieces are in place to allow support of non-sarracenia messages (talk to external systems).  This is about #615, and #617 mostly.
The work is mostly around this file:
postformat/wis.py   *postformat* has two other classes in it, v02.py, and v03.py for the two native sarracenia formats.  
In order to demonstrate encapsulation of foreign notification formats, using the wis one as an example.
It is defined here:
* https://github.com/wmo-im/wis2-notification-message/
* and there is some code to generate them here: https://github.com/wmo-im/pywis-pubsub
So what had to change?   The generation of a topic in Sarracenia is structured to be nearly automatic.  In other systems,  the way the *topic* field is generated will depend on the network itself, as well as some settings …
=> V03 issue615 - WIS format messages, as proof of concept of using non-sarracenia ones.

sarracenia/flow/__init__.py
Details in #709.
Before this change, files would only get renamed from their inflight name (e.g. filename.ext.tmp) when the downloaded size matched the expected size in the message.
When there is no size in the message, or the downloaded size is different, the files would not be renamed from their inflight name and later parts of the code would fail.
This ensures that the file gets renamed properly (and contentType gets set) when downloads are successful but the size is different than expected.
=> Fix #709 - properly handle downloaded files with size mismatches

sarracenia/config.py
while working on OpenDCS integration, need to declare an entire database (hundreds of lines of configuration) and every occurrence of the plugin specific module, when in debug results in t "possibly undeclared option" which is odd, but really only need to produce that message once, not for every time the option shows up.
So only print the message the first time each option is encourntered, not every time.
=> "possibly undeclared" option message should only be printed once.

tests/README.md, tests/requirements.txt, tests/sarracenia/__init___test.py
This test is pretty exhaustive, and probably overkill for the needs, but it's got 90% code coverage so that's pretty good.
There's some odd things that weren't able to provide coverage for though:
- `Message.dumps()`:
- Couldn't generate anything that wasn't printable, and thus fail the `try` on line 451
- `Message.fromFileInfo()`:
- It generates a new `msg` at every run, so couldn't get it to do the rename bits on lines 532-536. How sure how those are supposed to work
- Messages never have the `new_retrievePath` key, so the `if o.rename` block on lines 543-547 throws a key error if it runs (there's a test case for that though)
- Couldn't get the `try` on line 555 to fail no matter how many directories were striped, so the `except` never runs
- `Message.updatePaths()`:
- The `new_dir` and …
=> Sarracenia __init__ unit test

tests/sarracenia/diskqueue_test.py, tests/sarracenia/flowcb/nodupe/data_test.py, tests/sarracenia/flowcb/nodupe/disk_test.py, tests/sarracenia/flowcb/nodupe/name_test.py, tests/sarracenia/flowcb/nodupe/nodupe_test.py, tests/sarracenia/flowcb/nodupe/redis_test.py, tests/sarracenia/flowcb/retry_test.py, tests/sarracenia/flowcb/retry_teststeps.py, tests/sarracenia/redisqueue_test.py
In writing more and more tests, some things have been streamlined, or improved, and this is just back-porting those changes to previous tests.
- Define a `pretty` method that you can use while debugging your rests
- Use like: `pretty(ThingYouWantToDump)`, then run your tests with `-vv` and `--capture=tee-sys` parameters
- Move `Options` and `Message` creation into methods (versus creating objects manually)
- Should probably further use `sarracenia.config.default_config()` to generate base config
- Could also turn them both into a fixture, but then you might have to break each test set into it's own test method so the fixture resets properly
- Use `deepcopy` instead of just straight copy, so tests don't affect eachother
- With the changes above there was some broken tests in …
=> Update unit testing patterns

.github/workflows/flow.yml, .github/workflows/flow_basic.yml, sarracenia/credentials.py, sarracenia/moth/__init__.py, sarracenia/moth/mqtt.py, sarracenia/postformat/__init__.py, sarracenia/postformat/v02.py, sarracenia/postformat/v03.py
As per #415, adding support for mqtt over websockets (changes connect verb in use of paho-mqtt library)  This is done by adding w or ws to the broker URL  (mqtt:// is pure mqtt protocol, mqttws:// is mqtt over websockets (using SSL))
Also noticed why the flow tests were failing for MQTT, there was a mistake in handling of exchangeSplit, fixed in this branch.  MQTT might completely work after this is merged.
=> V03 issue415

sarracenia/sr.py
crash #724 of all sr3 (including just status) caused by funny state (nothing run, but configs and state directories present.)
=> fix, now it does not do that.

.github/workflows/flow.yml, .github/workflows/flow_basic.yml, sarracenia/config.py, sarracenia/credentials.py, sarracenia/flow/__init__.py, sarracenia/moth/__init__.py, sarracenia/moth/amqp.py, sarracenia/moth/mqtt.py, sarracenia/postformat/__init__.py, sarracenia/postformat/v02.py, sarracenia/postformat/v03.py, sarracenia/sr.py
So... I noticed... * plugins are not loaded by the *sr3 show* ... so the plugin defined options are listed as "possibly undefined." ....  to fix that, I needed to instantiate the flow class for the *show* command, and when I did that, it started initiating broker connections as part of the moth/* __init__ routines.  
So I needed to remove the broker connection from there, so that it just instantiated the object.  Once I did that, It's fine for get or put message stuff, because those check if the connection is still there, but for declare, need a new entry point...
so __getSetup() and __putSetup() lost their leading underscores to become public, and now in the *declare* action, we call .getSetup() ... or putSetup() whatever makes more sense.
This work needed the fixups to mqtt present in …
=> V03 issue720 -- fixing crash when a flag option is entered twice creating a list.

docs/source/Contribution/Development.rst, docs/source/Tutorials/Install.rst, docs/source/fr/Contribution/Développement.rst, docs/source/fr/Tutoriel/Installer.rst, sarracenia/__init__.py, sarracenia/flow/__init__.py, setup.py, travis/flow_autoconfig.sh
As explored in #721: There is a new feature in 3.0.42, where the content-type header of each file is included in the message... so people can know the filetype before downloading. It is a mandatory field in the WMO messages, so needed the functionality to be able to export cleanly, and itś a good thing anyways, so added it to base message format.
That required an additional dependency ¨python-magic" It turns out this dependency is troublesome. The debian packaged python packege is python3-magic, the pip install package name is python-magic but that only works on linux. on windows you need to install python-magic-bin. On linux, the debian package has a dependency on libmagic1, but if you install with pip, it won´t pull in the dep... and containers seem to be missing it. So in some cases …
=> V03 make *filetype* an sr3 extra feature, because of dependency issues.

tests/sarracenia/__init___test.py, tests/sarracenia/identity/_identity_test.py, tests/sarracenia/identity/arbitrary_test.py, tests/sarracenia/identity/md5_test.py, tests/sarracenia/identity/random_test.py, tests/sarracenia/identity/sha512_test.py
Wrote some during a demo with Peter and co., and finished the last couple after.
They have 100% coverage of all the identity stuff, which is fun.
=> Identity Unit tests

sarracenia/__init__.py, sarracenia/flow/__init__.py, sarracenia/moth/mqtt.py, sarracenia/postformat/v03.py, sarracenia/transfer/file.py
An element of getting MQTT to be reliable. At this point, the flakey test usually works, as does the dynamic, but the restart test always fails... with 29/36 tests passing.
The changes here makes it pass more tests, but does not fully resolve the issue.  It involves moving the paho.mqtt loop_start() method closer to the connection establishment, and as that caused issues in the tests, it is likely that these are good fixes.  I think it also improves the success rate of flakey... whereas before it passes sometimes, afterward it seems more reliable.
These fixes are likely to be helpful in and of themselves, and serve as a checkpoint for continued work.
Also included is the removal of *message corruption* in that some mqtt messages published included the *subtopic* field which was supposed …
=> V03 issue693 improve mqtt performance on restart_server flow test.

sarracenia/flow/__init__.py, sarracenia/flowcb/nodupe/__init__.py, sarracenia/flowcb/nodupe/disk.py, sarracenia/flowcb/nodupe/redis.py, tests/sarracenia/flowcb/nodupe/disk_test.py, tests/sarracenia/flowcb/nodupe/nodupe_test.py, tests/sarracenia/flowcb/nodupe/redis_test.py
This is a fix for #745, just changing the default key derivation.  The main idea was to change one if statement in deriveKey() method to change how key is derived for "cod" case,  But noticed that deriveKey in nodupe.disk.NoDupe and nodupe.redis.NoDupe are the same... there are two identical methods in two weirdly named classes.
Which revealed the need to refactor:
* re-create create sarracenia.flowcb.nodupe.NoDupe as parent class.
* the only method in the above class is deriveKey()
* sarracenia.nodupe.disk.NoDupe, is renamed to sarracenia.nodupe.disk.Disk (as per normal python practice) and it subclasses the parent  NoDupe class
* sarracenia.nodupe.redis.NoDupe, is renamed to sarracenia.nodupe.redis.Redis (as per normal python convention) and it subclasses the parent NoDupe class. …
=> V03 issue745 Improve poll cod deriveKey & refactor to remove code duplication

sarracenia/flowcb/accept/tohttp.py, sarracenia/flowcb/accept/tolocal.py, sarracenia/flowcb/accept/wmotypesuffix.py, tests/pytest.ini, tests/sarracenia/flowcb/accept/dateappend_test.py, tests/sarracenia/flowcb/accept/delete_test.py, tests/sarracenia/flowcb/accept/downloadbaseurl_test.py, tests/sarracenia/flowcb/accept/hourtree_test.py, tests/sarracenia/flowcb/accept/httptohttps_test.py, tests/sarracenia/flowcb/accept/longflow_test.py, tests/sarracenia/flowcb/accept/pathreplace_test.py, tests/sarracenia/flowcb/accept/posthourtree_test.py, tests/sarracenia/flowcb/accept/postoverride_test.py, tests/sarracenia/flowcb/accept/printlag_test.py, tests/sarracenia/flowcb/accept/rename4jicc_test.py, tests/sarracenia/flowcb/accept/renamedmf_test.py, tests/sarracenia/flowcb/accept/renamewhatfn_test.py, tests/sarracenia/flowcb/accept/save_test.py, tests/sarracenia/flowcb/accept/speedo_test.py, tests/sarracenia/flowcb/accept/sundowpxroute_test.py, tests/sarracenia/flowcb/accept/testretry_test.py, tests/sarracenia/flowcb/accept/toclusters_test.py, tests/sarracenia/flowcb/accept/tohttp_test.py, tests/sarracenia/flowcb/accept/tolocal_test.py, tests/sarracenia/flowcb/accept/tolocalfile_test.py, tests/sarracenia/flowcb/accept/trim_legacy_fields_test.py, tests/sarracenia/flowcb/accept/wmotypesuffix_test.py
This is a full test suite for all 23 FlowCB Accept plugins.
- Tests have 100% coverage
- It might be overkill, but the plugins were (mostly) simple, and getting perfect coverage wasn't much harder than 90+
- Some asserts are less than ideal (checking the number of log messages), as changes to other parts of the code could have negative effects
- Those asserts could be probably be removed, as I'm generally also checking that a particular message was logged, which is more telling
- Small config change to pytest, in order to ensure that only classes prefixed with `Test_` are treated as test classes (default is just `Test`)
Notable innovations with these tests
- Used [Paramaterized ](https://docs.pytest.org/en/7.1.x/example/parametrize.html) tests in with `wmotypesuffix_test.py`
- Very simple …
=> Unit tests for all Flowcb/Accept plugins

sarracenia/featuredetection.py
Formerly used importlib, but that only tested if the module itself was installed. As per #753, It turns out that import can fail because of transitive deps: a package is installed, but something that it depends on is missing, so it's clearer to just try an import surrounded by try/except.
=> fix #753, use try import rather than importlib to test module presence.

docs/source/Explanation/CommandLineGuide.rst, docs/source/Reference/sr3_options.7.rst, docs/source/fr/Explication/GuideLigneDeCommande.rst, docs/source/fr/Reference/sr3_options.7.rst, sarracenia/examples/flow/opg.conf, sarracenia/flowcb/clamav.py, sarracenia/flowcb/scheduled/__init__.py, sarracenia/flowcb/scheduled/wiski.py
as per #758 , add a proof of concept WISKI web services polling thing, supporting the token management needed by Ontario Power Generation.
* Generates tokens, supplies them to kiwis_pie (python wrapper module to access WISKI)
* polls the server given by *pollUrl*
* writes timeseries to a local directory given by *directory*
* generates posts using provided baseUrl etc... as per normal post/poll.
* implemented as a flowcb/scheduled plugin.  
* example configuration file provided.
* for testing, can be invoked on command line.
* works on linux and/or windows (different file naming conventions due restrictions on windows.)
generic items:
* noticed a bug in scheduled_intervals (applies to most of the ones deployed) fixed.
* found a bug in scheduled/init as well (missing argument would be …
=> 758 adding wiskis query support

sarracenia/moth/amqp.py
This makes some improvements but doesn't fix 732 yet. 
> It adds a timeout to publishing messages, which might help prevent hangs and improve error recovery when a broker isn't working. If the publish times out, it will raise an exception instead of hanging. The additional logging also helps troubleshooting - it was unclear where the publishing was getting stuck before.
> 
> The only thing missing is adding a timeout to the `self.channel.tx_commit()` call. We had talked about doing something similar to how timeouts are implemented here:
> 
> https://github.com/MetPX/sarracenia/blob/bcf4f4771f9c379722c3f9623f8341a12675ac4c/sarracenia/transfer/__init__.py#L60
https://github.com/MetPX/sarracenia/issues/732#issuecomment-1739903744
=> Add timeout to basic_publish and improve logging #732

sarracenia/flow/__init__.py
there is a small/rare case where the mirroring is not picking the right file as the source to be copied or renamed.
it is detailed in #772 . This problem is reported by the client doing the HPC mirroring.
The problem is that:
* when we create messages on the source, we do so with a current working directory at the root of the tree being copied.
* when we create files on the destinations, we chdir to the directory where we will create the file before writing it.
* when the path in a "link" or "rename" file operation is just a name, it refers to a file in the root (or baseDir) on the source side.
* on the destination need to add "../" to correct from the directory where the file is being created to find the same directory on the destination.
There was alreayd code for when the path had …
=> V03 issue772 rename bug in subscriber.

sarracenia/sr.py
=> Fix for #780, disabled configs prevents finding missing instances

sarracenia/moth/__init__.py, sarracenia/sr.py
fixes the display issues, there was an error calculating disconnection time making it a really large negative number if no connection had occurred.
also... -1 values were meant to be defaults for %ages when no data is available, but they look odd. replacing with 0%.
=> Correct metrics miscalculations. #783

sarracenia/sr.py
command line args to the launch of the flow were passed without the expansion already done in the code.  Need to replace with expanded values.
fix for:
```
fractal% sr3 foreground 'subsc*/*amis*'
.Traceback (most recent call last):
File "/home/peter/Sarracenia/sr3/sarracenia/instance.py", line 242, in <module>
i.start()
File "/home/peter/Sarracenia/sr3/sarracenia/instance.py", line 133, in start
cfg_preparse = sarracenia.config.one_config(component, config)
File "/home/peter/Sarracenia/sr3/sarracenia/config.py", line 2524, in one_config
os.chdir(component)
FileNotFoundError: [Errno 2] No such file or directory: 'subsc*'
2023-10-22 10:51:01,172 1853685 [CRITICAL] root run_command subprocess.run failed err=Command '['/usr/bin/python3', '/home/peter/Sarracenia/sr3/sarracenia/instance.py', …
```
=> V03 foreground with patterns won't start/is broken.

docs/source/Explanation/CommandLineGuide.rst, docs/source/How2Guides/Admin.rst, docs/source/How2Guides/UPGRADING.rst, docs/source/fr/CommentFaire/Admin.rst, docs/source/fr/CommentFaire/MiseANiveau.rst, docs/source/fr/Explication/GuideLigneDeCommande.rst, sarracenia/config.py, sarracenia/flow/__init__.py, sarracenia/flowcb/gather/message.py, sarracenia/instance.py, sarracenia/sr.py, tests/sarracenia/flowcb/accept/sundowpxroute_test.py
Have not been able to reproduce the problem. #784
The parsing of options for logBackup controlling rollover date to before there was option parsing.  It looks like there was some kind of typed parsing, and somehow a string was being passed to an option that expected an integer.
Revamped out the parsing is done, to just use the existing standard option parsing.  That involved changing the units of logBackupInterval, from days to being an ordinary interval (defaults to seconds, but can put 1d to get days.)
The commits here have the side effect of letting the client do something like:
```
logBackupInterval 30s
logBackupCount 3
```
to have the logs rollover every 30 seconds.  I need That to work on #785 
Before accepting the PR, should probably test on the system where it failed.
=> V03 issue784 (refactored/simplified logBackup parameter parsing.) also now can rollover every 30s

sarracenia/flow/__init__.py, sarracenia/flowcb/log.py, sarracenia/flowcb/v2wrapper.py, sarracenia/moth/amqp.py, sarracenia/postformat/__init__.py
When Daniel was working on a plugin to to minify input json files, it was publishing files
with a topic of just *v02.post* (stripping out the rest of the topic) so the consumers, being bound to a much longer topic, were not receiving the plugin's products. 
Last winter, there was code done to introduce postformat, so that networks other than native sarracenia messages could be supported (e.g. WMO WIS, ICAO SWIM) those protocols have different topic hierarchies, so need to make sarracenia able to flexibly deal with different postformats' topic schemes.
One way of doing that would be to have plugins set topics.  There is logic in postformat for to accept a topic header if it is provided.
It turned out that, when we have plugins from v2, we need to convert the message to v2, and that …
=> posts with too short topics (just v02.post)

sarracenia/config.py, sarracenia/instance.py, sarracenia/sr.py
* closes #793 
co-requisites:
* https://github.com/MetPX/sarrac/pull/117  - corresponding changes in C implementation.
* https://github.com/MetPX/sr_insects/pull/28 - corresponding changes in flow tests.
moves the metrics from being in the state file with the pid, queue, etc... files to it's
own directory parallel to the log directory.   This is more readily harvested by other tools and so is more integration friendly.
=> #793 - Move metrics to sub-directory (like logs)

.github/workflows/flow.yml, .github/workflows/flow_mqtt.yml, .github/workflows/flow_redis.yml, sarracenia/flow/__init__.py, sarracenia/flowcb/log.py, sarracenia/flowcb/poll/__init__.py, sarracenia/sr.py
There mirror processing in sarracenia/flow/__init__.py ... updateFieldsAccepted(...) routine had two problems with the mirror processing, that broke it quite thoroughly.
The real tragedy was that none of the flow tests caught it.
* closes #796 
* closes #791 
With the changes here, It will pass the tests in https://github.com/MetPX/sr_insects/pull/27
Things that were done:
* there was one line that didn't set relPath correctly for the mirror case.
* there was a second line that incorrectly override new_relPath.
Other stuff that had to be done to get working test cases:
* support of the self.o.fileEvents to choose which fileEvents to act one and forward was missing.
* had to fix up gaps in fileEvents processing in the built in downloading, the sender, and the poll.
=> fixes for mirror off and relPath settings from it.

sarracenia/sr.py
* closes #795 
not sure I understood @reidsunderland 's worry when he looked at it. I went into the _resolve routine, which is where it looks at stuff after all the data is collected.
Only the first spot seems to be effective, but saw a second spot where I think it should apply, but doesn't...  fixed both just in case.   should be used by both sanity and status.
=> found a way... it seems to work... would prefer reid looked at it.

sarracenia/config.py, sarracenia/flowcb/post/message.py
hey @andreleblanc11 ... maybe try this branch... I put the putSetup() in a on_Start in sarracenia/flowcb/post/message.py ... so it should solve the
bind before declare problem in any component.
closes #808
=> Issue808 setup on start

sarracenia/__init__.py, sarracenia/sr.py
closes #816 
Before this patch, if **timeCopy** was off, then a message would be created without *ctime* and *mtime* headers.  Now it is created, but the two headers are added to the *_deleteOnPost* header so they will not be forwarded.  The same thing was done for **permCopy**
So the code can validate that permissions in the poll are readable (because mode bits will be present), even though permCopy is off.   Code can also use the mtime/ctime as part of duplicate suppression or other time based filtering, even though timeCopy is off.
=> Issue816 - poll improve how permCopy/timeCopy work

sarracenia/moth/amqp.py, sarracenia/sr.py
* closes #649
* had to have the moth/amqp declare a second management channel... this one is synchronous, whereas on the normal data channel, there can be a lot of messages in flight.
* now every subscriber has two channels the normal one and the *management* one.
* plugged a call to queue declare in the metricsReport routine, but found it was called more often than I liked.
* added a timer to keep it from declaring the queue more than once every 30 seconds.
=> Issue649 - create a metric for broker side queued message count, and report in sr3 status

docs/source/How2Guides/subscriber.rst, docs/source/Reference/sr3_options.7.rst, docs/source/fr/CommentFaire/subscriber.rst, docs/source/fr/Reference/sr3_options.7.rst, sarracenia/flow/__init__.py
* closes #817 - makes logRotate parameters also affect the metrics files when logMetrics is active.
=> Issue817 - have logRotate* apply to metrics files too.

docs/source/Explanation/CommandLineGuide.rst, docs/source/Reference/sr3.1.rst, docs/source/Reference/sr3_cpump.1.rst, docs/source/fr/Explication/GuideLigneDeCommande.rst, docs/source/fr/Reference/sr3.1.rst, docs/source/fr/Reference/sr3_cpump.1.rst
closes #803
just remove all documentation of a setup command, which used to do something different than *declare* but today is just a synonym.
=> for #803: remove setup command, it is just an undocumented alias

.github/workflows/flow_amqp_consumer.yml, sarracenia/config.py, sarracenia/moth/__init__.py, sarracenia/moth/amqpconsumer.py
Adds a new Moth implementation that uses consumers instead of basic_get.
Enabled by setting `amqp_consumer True` in the config.
=> First attempt at switching to AMQP consumers instead of using basic_get

sarracenia/flowcb/log.py, sarracenia/moth/amqp.py, tests/sarracenia/config_test.py
* closes #828 
@andreleblanc11 ran into a case where it became obvious that when a component is subscribing and republishing, the post message prints the name of the exchange the message was received from, rather than the one it was posted to.
=> Issue828 - log message printing the wrong exchange.
